# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, conint, constr


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class Url(str, Enum):
    https___tile_openstreetmap_org__z___x___y__png = (
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
    )


class BaseMaps(BaseModel):
    url: Literal["https://tile.openstreetmap.org/{z}/{x}/{y}.png"] = Field(
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png", title="Preset Layer URL"
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url1(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Street_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps1(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url2(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Imagery_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"


class BaseMaps2(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url3(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Topo_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps3(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url4(str, Enum):
    https___tiles_arcgis_com_tiles_POUcpLYXNckpLjnY_arcgis_rest_services_landDx_basemap_tiles_mapservice_MapServer_tile__z___y___x_ = "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"


class BaseMaps4(BaseModel):
    url: Literal[
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url5(str, Enum):
    https___server_arcgisonline_com_arcgis_rest_services_Elevation_World_Hillshade_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"


class BaseMaps5(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class BaseMaps6(BaseModel):
    url: Optional[
        constr(
            pattern=r"https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\+.~#?&//=\{\}]*)"
        )
    ] = Field(
        "https://example.tiles.com/{z}/{x}/{y}.png",
        description="The URL of a publicly accessible tiled raster service.",
        title="Custom Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Custom Layer Opacity",
    )
    max_zoom: Optional[int] = Field(
        None,
        description="Set the maximum zoom level to fetch tiles for.",
        title="Custom Layer Max Zoom",
    )
    min_zoom: Optional[int] = Field(
        None,
        description="Set the minimum zoom level to fetch tiles for.",
        title="Custom Layer Min Zoom",
    )


class ConfigureBaseMaps(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base_maps: Optional[
        List[
            Union[
                BaseMaps,
                BaseMaps1,
                BaseMaps2,
                BaseMaps3,
                BaseMaps4,
                BaseMaps5,
                BaseMaps6,
            ]
        ]
    ] = Field(
        [
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
                "opacity": 1,
            },
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
                "opacity": 0.5,
            },
        ],
        description="Select tile layers to use as base layers in map outputs. The first layer in the list will be the bottommost layer displayed.",
        title=" ",
    )


class DownloadAteTpt(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    retries: Optional[conint(ge=0)] = Field(
        3, description="Number of retries on failure", title="Retries"
    )
    unzip: Optional[bool] = Field(
        False,
        description="Whether to unzip the file if it's a zip archive",
        title="Unzip",
    )


class GetSurveyEventsData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    include_null_geometry: Optional[bool] = Field(
        True, title="Include Events Without a Geometry (point or polygon)"
    )


class MapAgreeDisagree(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    inplace: Optional[bool] = Field(False, title="Inplace")


class MapYesNo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    inplace: Optional[bool] = Field(False, title="Inplace")


class MapColSurveys(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cols: Union[str, List[str]] = Field(..., title="Cols")


class ConvtToInt(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: Optional[str] = Field("coerce", title="Errors")
    fill_value: Optional[int] = Field(0, title="Fill Value")
    inplace: Optional[bool] = Field(False, title="Inplace")


class Filetype(str, Enum):
    csv = "csv"
    gpkg = "gpkg"
    geoparquet = "geoparquet"


class PersistDemoDf(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filetype: Optional[Filetype] = Field(
        "csv", description="The output format", title="Filetype"
    )


class BinSurveyCols(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bins: Optional[int] = Field(5, title="Bins")
    suffix: Optional[str] = Field(" bins", title="Suffix")
    inplace: Optional[bool] = Field(False, title="Inplace")


class FilterElephantQs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: Optional[str] = Field("raise", title="Errors")


class DrawLikertChart(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: Optional[str] = Field(None, title="Title")
    height_per_question: Optional[int] = Field(60, title="Height Per Question")
    min_height: Optional[int] = Field(400, title="Min Height")
    width: Optional[int] = Field(1200, title="Width")
    show_percentages: Optional[bool] = Field(True, title="Show Percentages")
    sort_questions: Optional[bool] = Field(False, title="Sort Questions")
    sort_by: Optional[str] = Field("positive", title="Sort By")


class FilterEffNoeff(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: Optional[str] = Field("raise", title="Errors")


class DrawLikertEff(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: Optional[str] = Field(None, title="Title")
    height_per_question: Optional[int] = Field(60, title="Height Per Question")
    min_height: Optional[int] = Field(400, title="Min Height")
    width: Optional[int] = Field(1200, title="Width")
    show_percentages: Optional[bool] = Field(True, title="Show Percentages")
    sort_questions: Optional[bool] = Field(False, title="Sort Questions")
    sort_by: Optional[str] = Field("positive", title="Sort By")


class FilterAttitudeCols(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: Optional[str] = Field("raise", title="Errors")


class PersistAttitudeDf(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filetype: Optional[Filetype] = Field(
        "csv", description="The output format", title="Filetype"
    )


class FilterStatQs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    errors: Optional[str] = Field("raise", title="Errors")


class PersistAnovaDf(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filetype: Optional[Filetype] = Field(
        "csv", description="The output format", title="Filetype"
    )


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class TemporalGrouper(RootModel[str]):
    root: str = Field(..., title="Time")


class ValueGrouper(RootModel[str]):
    root: str = Field(..., title="Category")


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class Sort(str, Enum):
    ascending = "ascending"
    descending = "descending"


class LegendDefinition(BaseModel):
    label_column: Optional[str] = Field(None, title="Label Column")
    color_column: Optional[str] = Field(None, title="Color Column")
    labels: Optional[List[str]] = Field(None, title="Labels")
    colors: Optional[List[str]] = Field(None, title="Colors")
    sort: Optional[Sort] = Field(None, title="Sort")
    label_suffix: Optional[str] = Field(None, title="Label Suffix")


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: Optional[List[Union[ValueGrouper, TemporalGrouper]]] = Field(
        None,
        description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
        title=" ",
    )


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class GenerateAttLayers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    legend: Optional[LegendDefinition] = Field(
        None,
        description="If present, includes this layer in the map legend",
        title="Legend",
    )
    tooltip_columns: Optional[List[str]] = Field(
        None,
        description="If present, only the listed dataframe columns will display in the layer's picking info",
        title="Tooltip Columns",
    )


class GenerateGnLayers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    legend: Optional[LegendDefinition] = Field(
        None,
        description="If present, includes this layer in the map legend",
        title="Legend",
    )
    tooltip_columns: Optional[List[str]] = Field(
        None,
        description="If present, only the listed dataframe columns will display in the layer's picking info",
        title="Tooltip Columns",
    )


class GenerateOvLayers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    legend: Optional[LegendDefinition] = Field(
        None,
        description="If present, includes this layer in the map legend",
        title="Legend",
    )
    tooltip_columns: Optional[List[str]] = Field(
        None,
        description="If present, only the listed dataframe columns will display in the layer's picking info",
        title="Tooltip Columns",
    )


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set workflow details",
    )
    time_range: Optional[TimeRange] = Field(
        None,
        description="Choose the period of time to analyze.",
        title="Set time range",
    )
    groupers: Optional[Groupers] = Field(None, title="Set groupers")
    er_client_name: Optional[ErClientName] = Field(None, title="Connect to ER")
    configure_base_maps: Optional[ConfigureBaseMaps] = Field(
        None, title="Configure basemap layers"
    )
    download_ate_tpt: Optional[DownloadAteTpt] = Field(
        None, title="Download ATE survey template"
    )
    get_survey_events_data: Optional[GetSurveyEventsData] = Field(
        None, title="Retrieve ate survey events"
    )
    map_agree_disagree: Optional[MapAgreeDisagree] = Field(
        None, title="Map Agree/Disagree columns"
    )
    map_yes_no: Optional[MapYesNo] = Field(None, title="Map Yes/No columns")
    map_col_surveys: Optional[MapColSurveys] = Field(None, title="Map survey columns")
    convt_to_int: Optional[ConvtToInt] = Field(None, title="Convert columns to int")
    persist_demo_df: Optional[PersistDemoDf] = Field(
        None, title="Persist demographic table to disk"
    )
    bin_survey_cols: Optional[BinSurveyCols] = Field(
        None, title="Bin columns on survey"
    )
    filter_elephant_qs: Optional[FilterElephantQs] = Field(
        None, title="Filter elephant relevant questions"
    )
    draw_likert_chart: Optional[DrawLikertChart] = Field(
        None, title="Draw likert chart"
    )
    filter_eff_noeff: Optional[FilterEffNoeff] = Field(
        None, title="Filter effective / not effective df"
    )
    draw_likert_eff: Optional[DrawLikertEff] = Field(None, title="Draw likert chart")
    filter_attitude_cols: Optional[FilterAttitudeCols] = Field(
        None, title="Filter attitude score columns"
    )
    persist_attitude_df: Optional[PersistAttitudeDf] = Field(
        None, title="Persist attitude scores df"
    )
    filter_stat_qs: Optional[FilterStatQs] = Field(
        None, title="Filter stat relevant questions"
    )
    persist_anova_df: Optional[PersistAnovaDf] = Field(
        None, title="Persist anova df to disk"
    )
    generate_att_layers: Optional[GenerateAttLayers] = Field(
        None, title="Generate attitude score point layers"
    )
    generate_gn_layers: Optional[GenerateGnLayers] = Field(
        None, title="Generate gender point layers"
    )
    generate_ov_layers: Optional[GenerateOvLayers] = Field(
        None, title="Generate overall point layers"
    )
