# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Ate Survey
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import set_workflow_details
from ecoscope_workflows_core.tasks.filter import set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers
from ecoscope_workflows_core.tasks.io import persist_text, set_er_connection
from ecoscope_workflows_core.tasks.results import gather_dashboard
from ecoscope_workflows_core.tasks.skip import any_dependency_skipped, any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import map_columns
from ecoscope_workflows_ext_ate.tasks import (
    bin_columns,
    calculate_elephant_sentiment_score,
    combine_map_layers,
    convert_object_to_string,
    convert_object_to_value,
    convert_to_int,
    create_likert_chart,
    create_map_layers,
    create_view_state_from_gdf,
    download_file_and_persist,
    draw_bar_and_persist,
    draw_boxplot_and_persist,
    draw_ols_scatterplot_and_persist,
    draw_pie_and_persist,
    draw_tukey_plots_and_persist,
    exclude_geom_outliers,
    exclude_value,
    fill_missing_values,
    filter_cols_df,
    format_demographic_table,
    load_geospatial_files,
    map_survey_columns,
    map_survey_responses,
    merge_dataframes,
    perform_anova_analysis,
    view_df,
    zhtml_to_png,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events, persist_df
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_point_layer,
    draw_ecomap,
    set_base_maps,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map,
    normalize_column,
)

# %% [markdown]
# ## Set workflow details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.handle_errors(task_instance_id="workflow_details")
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Set time range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.handle_errors(task_instance_id="time_range")
    .partial(time_format="%d %b %Y %H:%M:%S %Z", **time_range_params)
    .call()
)


# %% [markdown]
# ## Set groupers

# %%
# parameters

groupers_params = dict(
    groupers=...,
)

# %%
# call the task


groupers = (
    set_groupers.handle_errors(task_instance_id="groupers")
    .partial(**groupers_params)
    .call()
)


# %% [markdown]
# ## Connect to ER

# %%
# parameters

er_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


er_client_name = (
    set_er_connection.handle_errors(task_instance_id="er_client_name")
    .partial(**er_client_name_params)
    .call()
)


# %% [markdown]
# ## Configure basemap layers

# %%
# parameters

configure_base_maps_params = dict(
    base_maps=...,
)

# %%
# call the task


configure_base_maps = (
    set_base_maps.handle_errors(task_instance_id="configure_base_maps")
    .partial(**configure_base_maps_params)
    .call()
)


# %% [markdown]
# ## Download ATE survey template

# %%
# parameters

download_ate_tpt_params = dict(
    retries=...,
    unzip=...,
)

# %%
# call the task


download_ate_tpt = (
    download_file_and_persist.handle_errors(task_instance_id="download_ate_tpt")
    .partial(
        url="https://www.dropbox.com/scl/fi/8eig0iyg2uu76eghi2sd4/ate_survey_template.docx?rlkey=pe5dpqnskj60v0b5uchocdpy1&st=zdokeegg&dl=0",
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        overwrite_existing=False,
        **download_ate_tpt_params,
    )
    .call()
)


# %% [markdown]
# ## Download amboseli ecosystem shapefiles

# %%
# parameters

dowwnload_ambo_eco_params = dict(
    retries=...,
    unzip=...,
)

# %%
# call the task


dowwnload_ambo_eco = (
    download_file_and_persist.handle_errors(task_instance_id="dowwnload_ambo_eco")
    .partial(
        url="https://www.dropbox.com/scl/fi/3yvgk7va9pxm1k3qe5aue/Amboseli-Ecosystem.gpkg?rlkey=nx9udkzvghxxz76rzl5dgx922&st=14pq6124&dl=0",
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        overwrite_existing=False,
        **dowwnload_ambo_eco_params,
    )
    .call()
)


# %% [markdown]
# ## Download amboseli ranch boundaries shapefiles

# %%
# parameters

dowwnload_ranch_bnds_params = dict(
    retries=...,
    unzip=...,
)

# %%
# call the task


dowwnload_ranch_bnds = (
    download_file_and_persist.handle_errors(task_instance_id="dowwnload_ranch_bnds")
    .partial(
        url="https://www.dropbox.com/scl/fi/b4yckfk2t077bhigb1k07/Amboseli-Ranch-Boundaries.gpkg?rlkey=kxiehp8f73j3y5g792jstwo0z&st=6hb6qwj9&dl=0",
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        overwrite_existing=False,
        **dowwnload_ranch_bnds_params,
    )
    .call()
)


# %% [markdown]
# ## Download amboseli swamps shapefiles

# %%
# parameters

dowwnload_ambo_sws_params = dict(
    retries=...,
    unzip=...,
)

# %%
# call the task


dowwnload_ambo_sws = (
    download_file_and_persist.handle_errors(task_instance_id="dowwnload_ambo_sws")
    .partial(
        url="https://www.dropbox.com/scl/fi/1x5imkkvesnxv35kp8ngw/Amboseli-Swamps.gpkg?rlkey=n5rtu313zh0cg7o0cmbbt1jf4&st=zebggl8l&dl=0",
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        overwrite_existing=False,
        **dowwnload_ambo_sws_params,
    )
    .call()
)


# %% [markdown]
# ## Download national parks shapefiles

# %%
# parameters

dowwnload_np_shp_params = dict(
    retries=...,
    unzip=...,
)

# %%
# call the task


dowwnload_np_shp = (
    download_file_and_persist.handle_errors(task_instance_id="dowwnload_np_shp")
    .partial(
        url="https://www.dropbox.com/scl/fi/7txo6s0tof8j0jp7j7lgk/National-Parks.gpkg?rlkey=yemiaztgu5scvlcdwapbkek9j&st=m9lz6abw&dl=0",
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        overwrite_existing=False,
        **dowwnload_np_shp_params,
    )
    .call()
)


# %% [markdown]
# ## Load local map files

# %%
# parameters

load_local_shapefiles_params = dict()

# %%
# call the task


load_local_shapefiles = (
    load_geospatial_files.handle_errors(task_instance_id="load_local_shapefiles")
    .partial(
        config={"path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"]},
        **load_local_shapefiles_params,
    )
    .call()
)


# %% [markdown]
# ## Create Map Layers

# %%
# parameters

create_custom_map_layers_params = dict()

# %%
# call the task


create_custom_map_layers = (
    create_map_layers.handle_errors(task_instance_id="create_custom_map_layers")
    .partial(
        file_dict=load_local_shapefiles,
        style_config={
            "styles": {
                "amboseli_ecosystem": {
                    "get_elevation": 1000,
                    "get_fill_color": "#FFFFFF00",
                    "get_line_color": "#696969",
                    "get_line_width": 3,
                    "opacity": 0.75,
                    "stroked": True,
                },
                "amboseli_ranch_boundaries": {
                    "get_elevation": 1000,
                    "get_fill_color": "#FFFFFF00",
                    "get_line_color": "#000000",
                    "get_line_width": 2,
                    "stroked": True,
                    "opacity": 0.25,
                },
                "amboseli_swamps": {
                    "get_elevation": 1000,
                    "get_fill_color": "#609cb5",
                    "get_line_color": "#609cb5",
                    "get_line_width": 2,
                    "stroked": True,
                    "opacity": 0.25,
                },
                "national_parks": {
                    "fill_color": "#4c8c2b",
                    "line_color": "#4c8c2b",
                    "line_width": 2,
                    "stroked": True,
                    "fill_opacity": 0.25,
                },
            },
            "legend": {
                "labels": [
                    "Amboseli Ecosystem",
                    "Amboseli Ranch Boundaries",
                    "Amboseli Swamps",
                    "National Parks",
                ],
                "colors": ["#41b6c4", "#f03b20", "#006d2c", "#6a51a3"],
            },
        },
        **create_custom_map_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Retrieve ate survey events

# %%
# parameters

get_survey_events_data_params = dict(
    include_null_geometry=...,
)

# %%
# call the task


get_survey_events_data = (
    get_events.handle_errors(task_instance_id="get_survey_events_data")
    .partial(
        client=er_client_name,
        time_range=time_range,
        event_columns=[
            "id",
            "time",
            "event_type",
            "event_category",
            "reported_by",
            "serial_number",
            "geometry",
            "created_at",
            "event_details",
        ],
        event_types=["atequestionnaire_rep"],
        raise_on_empty=False,
        include_details=True,
        include_updates=False,
        include_related_events=False,
        **get_survey_events_data_params,
    )
    .call()
)


# %% [markdown]
# ## Exclude id value from df

# %%
# parameters

exclude_val_id_params = dict()

# %%
# call the task


exclude_val_id = (
    exclude_value.handle_errors(task_instance_id="exclude_val_id")
    .partial(
        df=get_survey_events_data,
        column="serial_number",
        value=46283,
        **exclude_val_id_params,
    )
    .call()
)


# %% [markdown]
# ## Normalize event details column

# %%
# parameters

normalize_event_details_params = dict()

# %%
# call the task


normalize_event_details = (
    normalize_column.handle_errors(task_instance_id="normalize_event_details")
    .partial(
        column="event_details", df=exclude_val_id, **normalize_event_details_params
    )
    .call()
)


# %% [markdown]
# ## Retain columns and rename columns

# %%
# parameters

rename_survey_columns_params = dict()

# %%
# call the task


rename_survey_columns = (
    map_columns.handle_errors(task_instance_id="rename_survey_columns")
    .partial(
        df=normalize_event_details,
        drop_columns=[
            "event_category",
            "reported_by",
            "event_details__updates",
            "event_details__end_time",
            "event_details__closing_statement",
            "event_details__participant_occupationifother",
            "event_details__livestock_health_1_otheranimals",
            "event_details__livestock_health_3_otheranimals",
            "event_details__participant_tribeifother",
            "event_details__participant_land_tenureifother",
            "event_details__behaviour_2",
            "event_details__behaviour_4_ifyes",
            "event_details__one_health_7",
            "event_details__livestock_health_4",
            "event_details__livestock_health_5",
            "event_details__livestock_health_6",
            "event_details__behaviour_killing_2",
            "event_details__behaviour_killing_3",
            "event_details__perception_challenges",
            "event_details__participant_occupation",
            "event_details__water_mitigation_use_2",
            "event_details__livestock_health_3_cattle",
            "event_details__livestock_health_3_donkies",
            "event_details__livestock_health_3_sheepgoat",
            "event_details__perception_conservation_interventions_6",
            "event_details__perception_conservation_interventions_4ifyes",
            "event_details__perception_conservation_interventions_2_ifnowhy",
            "event_details__belief_costs_4",
            "event_details__belief_benefits_4",
            "event_details__crop_mitigation_2",
            "event_details__perception_crop_production_threatsifother",
            "event_details__perception_conservation_interventions_5ifother",
            "event_details__one_health_8_ifyes",
            "event_details__participant_tribeifother",
            "event_details__participant_land_tenureifother",
            "event_details__livestock_health_3_dogs",
        ],
        retain_columns=[],
        rename_columns={
            "event_details__participant_age": "Participant age",
            "event_details__participant_tribe": "Participant tribe",
            "event_details__participant_gender": "Participant gender",
            "event_details__elephant_knowledge_1": "Female elephants live in family groups",
            "event_details__elephant_knowledge_2": "Female elephants protect their young",
            "event_details__participant_num_cows": "Number of cows",
            "event_details__participant_age_range": "Participant age group",
            "event_details__participant_agreement": "Respondent agreed to interview",
            "event_details__participant_household": "Household size",
            "event_details__participant_land_owned": "Land owned (acres)",
            "event_details__participant_num_shoats": "Number of shoats",
            "event_details__participant_agricultural_land": "Agricultural land (acres)",
            "event_details__participant_duration_in_amboseli": "Years living in area",
            "event_details__belief_1": "Humans and elephants can live together",
            "event_details__attitude_0": "Overall feelings about wildlife",
            "event_details__attitude_1": "Opinion on having elephants in the area",
            "event_details__attitude_2": "Importance of elephants living here",
            "event_details__attitude_3": "Elephants should only live inside parks",
            "event_details__exposure_1": "How often seen elephants in the last year",
            "event_details__exposure_2": "See more elephants now than before",
            "event_details__behaviour_1": "Do you change routes or schedules because of elephants",
            "event_details__behaviour_3": "Effectiveness rating of that practice",
            "event_details__behaviour_4": "What do you do when you encounter elephants on foot",
            "event_details__one_health_8": "Noticed signs of illness in wild animals",
            "event_details__belief_costs_1": "Elephants harm community members",
            "event_details__belief_costs_2": "Elephants negatively affect my livelihood",
            "event_details__belief_costs_3": "Elephants impact my emotional wellbeing",
            "event_details__future_activity": "Willingness to join future community dialogue",
            "event_details__attitude_killing": "Reaction to hearing about elephants being harmed",
            "event_details__belief_benefits_1": "Receive livelihood benefits from elephants",
            "event_details__belief_benefits_2": "Benefit from enjoying seeing elephants",
            "event_details__belief_benefits_3": "Elephants are important for a healthy ecosystem",
            "event_details__crop_mitigation_1": "Use measures to protect crops from elephants",
            "event_details__behaviour_killing_1": "Ever been involved in or witnessed an elephant harmed",
            "event_details__hazard_acceptance_1": "Acceptable to harm elephants if they damage property or livestock",
            "event_details__hazard_acceptance_2": "Acceptable to harm elephants if people are hurt",
            "event_details__elephant_knowledge_3": "Elephants can smell and hear from far away",
            "event_details__elephant_knowledge_4": "Elephants move seasonally for food and water",
            "event_details__elephant_knowledge_6": "Elephant may shake its head when annoyed",
            "event_details__elephant_knowledge_7": "Elephant signals awareness by raising trunk",
            "event_details__elephant_knowledge_8": "Male elephants with secretions may be more aggressive",
            "event_details__participant_education": "Highest level of education",
            "event_details__livestock_mitigation_1": "Use measures to protect livestock from elephants",
            "event_details__water_mitigation_use_1": "Protect water sources from elephants",
            "event_details__water_mitigation_use_3": "Effectiveness rating of water protection",
            "event_details__livestock_health_1_dogs": "Number of dogs",
            "event_details__participant_land_tenure": "Land tenure",
            "event_details__livestock_health_1_cattle": "Number of cattle",
            "event_details__livestock_health_1_donkies": "Number of donkeys",
            "event_details__participant_marital_status": "Marital status",
            "event_details__livestock_health_1_sheepgoat": "Number of sheep or goats",
            "event_details__perception_livestock_threats": "Greatest threat to your livestock",
            "event_details__perception_crop_production_threats": "Greatest threat to crop production",
            "event_details__perception_conservation_interventions_1": "Benefit from the KCCDT Big Life electric fence",
            "event_details__perception_conservation_interventions_2": "Pay into fence maintenance fund",
            "event_details__perception_conservation_interventions_4": "Do you report elephant conflict incidents",
            "event_details__perception_conservation_interventions_5": "Which intervention would help you in future",
            "event_details__crop_mitigation_3": "Effectiveness rating of primary crop protection method",
            "event_details__livestock_mitigation_2": "If yes, which methods do you use for livestock",
        },
        **rename_survey_columns_params,
    )
    .call()
)


# %% [markdown]
# ## Convert objects to number

# %%
# parameters

convert_obj_to_num_params = dict()

# %%
# call the task


convert_obj_to_num = (
    convert_object_to_value.handle_errors(task_instance_id="convert_obj_to_num")
    .partial(
        df=rename_survey_columns,
        columns=[
            "Participant age",
            "Number of cows",
            "Household size",
            "Land owned (acres)",
            "Number of shoats",
            "Agricultural land (acres)",
            "Number of sheep or goats",
            "Number of dogs",
            "Number of cattle",
            "Number of donkeys",
        ],
        **convert_obj_to_num_params,
    )
    .call()
)


# %% [markdown]
# ## Convert objects to string

# %%
# parameters

convert_obj_to_str_params = dict()

# %%
# call the task


convert_obj_to_str = (
    convert_object_to_string.handle_errors(task_instance_id="convert_obj_to_str")
    .partial(
        df=convert_obj_to_num,
        columns=[
            "id",
            "Participant tribe",
            "Participant gender",
            "Female elephants live in family groups",
            "Female elephants protect their young",
            "Participant age group",
            "Respondent agreed to interview",
            "Years living in area",
            "Humans and elephants can live together",
            "Overall feelings about wildlife",
            "Opinion on having elephants in the area",
            "Importance of elephants living here",
            "Elephants should only live inside parks",
            "How often seen elephants in the last year",
            "See more elephants now than before",
            "Do you change routes or schedules because of elephants",
            "Effectiveness rating of that practice",
            "What do you do when you encounter elephants on foot",
            "Noticed signs of illness in wild animals",
            "Elephants harm community members",
            "Elephants negatively affect my livelihood",
            "Elephants impact my emotional wellbeing",
            "Willingness to join future community dialogue",
            "Reaction to hearing about elephants being harmed",
            "Receive livelihood benefits from elephants",
            "Benefit from enjoying seeing elephants",
            "Elephants are important for a healthy ecosystem",
            "Use measures to protect crops from elephants",
            "Ever been involved in or witnessed an elephant harmed",
            "Acceptable to harm elephants if they damage property or livestock",
            "Acceptable to harm elephants if people are hurt",
            "Elephants can smell and hear from far away",
            "Elephants move seasonally for food and water",
            "Elephant may shake its head when annoyed",
            "Elephant signals awareness by raising trunk",
            "Male elephants with secretions may be more aggressive",
            "Highest level of education",
            "Use measures to protect livestock from elephants",
            "Protect water sources from elephants",
            "Effectiveness rating of water protection",
            "Land tenure",
            "Marital status",
            "Greatest threat to your livestock",
            "Greatest threat to crop production",
            "Benefit from the KCCDT Big Life electric fence",
            "Pay into fence maintenance fund",
            "Do you report elephant conflict incidents",
            "Which intervention would help you in future",
            "Effectiveness rating of primary crop protection method",
            "If yes, which methods do you use for livestock",
        ],
        **convert_obj_to_str_params,
    )
    .call()
)


# %% [markdown]
# ## Fill missing values with default values

# %%
# parameters

fill_values_params = dict()

# %%
# call the task


fill_values = (
    fill_missing_values.handle_errors(task_instance_id="fill_values")
    .partial(
        dataframe=convert_obj_to_str,
        numeric_fill_value=0,
        categorical_fill_value="Unspecified",
        numeric_columns=[
            "Participant age",
            "Number of cows",
            "Household size",
            "Land owned (acres)",
            "Number of shoats",
            "Agricultural land (acres)",
            "Number of sheep or goats",
            "Number of dogs",
            "Number of cattle",
            "Number of donkeys",
        ],
        categorical_columns=[
            "id",
            "Participant tribe",
            "Participant gender",
            "Female elephants live in family groups",
            "Female elephants protect their young",
            "Participant age group",
            "Respondent agreed to interview",
            "Years living in area",
            "Humans and elephants can live together",
            "Overall feelings about wildlife",
            "Opinion on having elephants in the area",
            "Importance of elephants living here",
            "Elephants should only live inside parks",
            "How often seen elephants in the last year",
            "See more elephants now than before",
            "Do you change routes or schedules because of elephants",
            "Effectiveness rating of that practice",
            "What do you do when you encounter elephants on foot",
            "Noticed signs of illness in wild animals",
            "Elephants harm community members",
            "Elephants negatively affect my livelihood",
            "Elephants impact my emotional wellbeing",
            "Willingness to join future community dialogue",
            "Reaction to hearing about elephants being harmed",
            "Receive livelihood benefits from elephants",
            "Benefit from enjoying seeing elephants",
            "Elephants are important for a healthy ecosystem",
            "Use measures to protect crops from elephants",
            "Ever been involved in or witnessed an elephant harmed",
            "Acceptable to harm elephants if they damage property or livestock",
            "Acceptable to harm elephants if people are hurt",
            "Elephants can smell and hear from far away",
            "Elephants move seasonally for food and water",
            "Elephant may shake its head when annoyed",
            "Elephant signals awareness by raising trunk",
            "Male elephants with secretions may be more aggressive",
            "Highest level of education",
            "Use measures to protect livestock from elephants",
            "Protect water sources from elephants",
            "Effectiveness rating of water protection",
            "Land tenure",
            "Marital status",
            "Greatest threat to your livestock",
            "Greatest threat to crop production",
            "Benefit from the KCCDT Big Life electric fence",
            "Pay into fence maintenance fund",
            "Do you report elephant conflict incidents",
            "Which intervention would help you in future",
            "Effectiveness rating of primary crop protection method",
            "If yes, which methods do you use for livestock",
        ],
        **fill_values_params,
    )
    .call()
)


# %% [markdown]
# ## Map Agree/Disagree columns

# %%
# parameters

map_agree_disagree_params = dict(
    inplace=...,
)

# %%
# call the task


map_agree_disagree = (
    map_survey_responses.handle_errors(task_instance_id="map_agree_disagree")
    .partial(
        df=fill_values,
        columns=[
            "Humans and elephants can live together",
            "Importance of elephants living here",
            "Elephants should only live inside parks",
            "Elephants harm community members",
            "Elephants negatively affect my livelihood",
            "Elephants impact my emotional wellbeing",
            "Benefit from enjoying seeing elephants",
            "Elephants are important for a healthy ecosystem",
            "Acceptable to harm elephants if they damage property or livestock",
            "Acceptable to harm elephants if people are hurt",
            "Receive livelihood benefits from elephants",
        ],
        value_map={
            "strongly_agree": "Strongly agree",
            "agree": "Agree",
            "neutral": "Neutral",
            "disagree": "Disagree",
            "strongly_disagree": "Strongly disagree",
            "i_dont_know": "I don't know",
            "prefer_not_to_answer": "Prefer not to answer",
        },
        **map_agree_disagree_params,
    )
    .call()
)


# %% [markdown]
# ## Map true false columns

# %%
# parameters

map_true_false_params = dict(
    inplace=...,
)

# %%
# call the task


map_true_false = (
    map_survey_responses.handle_errors(task_instance_id="map_true_false")
    .partial(
        df=map_agree_disagree,
        columns=[
            "Female elephants live in family groups",
            "Female elephants protect their young",
            "Elephants move seasonally for food and water",
            "Elephant may shake its head when annoyed",
            "Elephant signals awareness by raising trunk",
            "Male elephants with secretions may be more aggressive",
            "Elephants can smell and hear from far away",
        ],
        value_map={"false": "False", "true": "True", "i_dont_know": "I don't know"},
        **map_true_false_params,
    )
    .call()
)


# %% [markdown]
# ## Map effective/not effective columns

# %%
# parameters

map_no_effect_params = dict(
    inplace=...,
)

# %%
# call the task


map_no_effect = (
    map_survey_responses.handle_errors(task_instance_id="map_no_effect")
    .partial(
        df=map_true_false,
        columns=[
            "Effectiveness rating of primary crop protection method",
            "Effectiveness rating of that practice",
            "Effectiveness rating of water protection",
        ],
        value_map={
            "highly_effective": "Highly effective",
            "effective": "Effective",
            "not_effective": "Not effective",
            "i_dont_know": "I don't know",
        },
        **map_no_effect_params,
    )
    .call()
)


# %% [markdown]
# ## Map survey columns

# %%
# parameters

map_col_surveys_params = dict()

# %%
# call the task


map_col_surveys = (
    map_survey_columns.handle_errors(task_instance_id="map_col_surveys")
    .partial(
        df=map_no_effect,
        cols=[
            "Participant age",
            "Household size",
            "Participant tribe",
            "Participant gender",
            "Participant age group",
            "Years living in area",
            "Overall feelings about wildlife",
            "Opinion on having elephants in the area",
            "How often seen elephants in the last year",
            "What do you do when you encounter elephants on foot",
            "Reaction to hearing about elephants being harmed",
            "Highest level of education",
            "Greatest threat to your livestock",
            "Greatest threat to crop production",
            "Which intervention would help you in future",
            "Marital status",
            "Land tenure",
            "Humans and elephants can live together",
            "Importance of elephants living here",
            "Elephants should only live inside parks",
            "Elephants harm community members",
            "Elephants negatively affect my livelihood",
            "Elephants impact my emotional wellbeing",
            "Benefit from enjoying seeing elephants",
            "Elephants are important for a healthy ecosystem",
            "Acceptable to harm elephants if they damage property or livestock",
            "Acceptable to harm elephants if people are hurt",
            "Receive livelihood benefits from elephants",
        ],
        **map_col_surveys_params,
    )
    .call()
)


# %% [markdown]
# ## Print mapped values

# %%
# parameters

print_mapped_df_params = dict()

# %%
# call the task


print_mapped_df = (
    view_df.handle_errors(task_instance_id="print_mapped_df")
    .partial(
        gdf=map_col_surveys, name="View presently mapped df", **print_mapped_df_params
    )
    .call()
)


# %% [markdown]
# ## Convert columns to int

# %%
# parameters

convt_to_int_params = dict(
    errors=...,
    fill_value=...,
    inplace=...,
)

# %%
# call the task


convt_to_int = (
    convert_to_int.handle_errors(task_instance_id="convt_to_int")
    .partial(
        df=map_col_surveys,
        columns=[
            "Participant age",
            "Number of cows",
            "Household size",
            "Number of shoats",
            "Agricultural land (acres)",
            "Number of sheep or goats",
            "Number of dogs",
            "Number of cattle",
            "Number of donkeys",
        ],
        **convt_to_int_params,
    )
    .call()
)


# %% [markdown]
# ## Create demographic table

# %%
# parameters

create_demo_table_params = dict()

# %%
# call the task


create_demo_table = (
    format_demographic_table.handle_errors(task_instance_id="create_demo_table")
    .partial(
        df=convt_to_int,
        columns_of_interest=[
            "Participant gender",
            "Participant age",
            "Participant tribe",
            "Household size",
            "Highest level of education",
        ],
        **create_demo_table_params,
    )
    .call()
)


# %% [markdown]
# ## Persist demographic table to disk

# %%
# parameters

persist_demo_df_params = dict(
    filetype=...,
)

# %%
# call the task


persist_demo_df = (
    persist_df.handle_errors(task_instance_id="persist_demo_df")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        df=create_demo_table,
        filename="demographic_table",
        **persist_demo_df_params,
    )
    .call()
)


# %% [markdown]
# ## Bin columns on survey

# %%
# parameters

bin_survey_cols_params = dict(
    bins=...,
    suffix=...,
    inplace=...,
)

# %%
# call the task


bin_survey_cols = (
    bin_columns.handle_errors(task_instance_id="bin_survey_cols")
    .partial(
        df=convt_to_int,
        columns=[
            "Participant age",
            "Number of cows",
            "Household size",
            "Number of shoats",
            "Land owned (acres)",
            "Agricultural land (acres)",
            "Number of dogs",
            "Number of cattle",
            "Number of donkeys",
            "Number of sheep or goats",
        ],
        **bin_survey_cols_params,
    )
    .call()
)


# %% [markdown]
# ## Filter elephant relevant questions

# %%
# parameters

filter_elephant_qs_params = dict(
    errors=...,
)

# %%
# call the task


filter_elephant_qs = (
    filter_cols_df.handle_errors(task_instance_id="filter_elephant_qs")
    .partial(
        df=bin_survey_cols,
        cols=[
            "Humans and elephants can live together",
            "Importance of elephants living here",
            "Elephants should only live inside parks",
            "Elephants harm community members",
            "Elephants negatively affect my livelihood",
            "Elephants impact my emotional wellbeing",
            "Benefit from enjoying seeing elephants",
            "Elephants are important for a healthy ecosystem",
            "Acceptable to harm elephants if they damage property or livestock",
            "Acceptable to harm elephants if people are hurt",
            "Receive livelihood benefits from elephants",
        ],
        **filter_elephant_qs_params,
    )
    .call()
)


# %% [markdown]
# ## Draw likert chart

# %%
# parameters

draw_likert_chart_params = dict(
    title=...,
    height_per_question=...,
    min_height=...,
    width=...,
    show_percentages=...,
    sort_questions=...,
    sort_by=...,
)

# %%
# call the task


draw_likert_chart = (
    create_likert_chart.handle_errors(task_instance_id="draw_likert_chart")
    .partial(
        df=filter_elephant_qs,
        response_order=[
            "Strongly disagree",
            "Disagree",
            "Neutral",
            "Agree",
            "Strongly agree",
        ],
        neutral_categories=["Neutral"],
        colors={
            "Strongly disagree": "#2c5282",
            "Disagree": "#4299e1",
            "Neutral": "#a0aec0",
            "Unspecified": "#a0aec0",
            "I don't know": "#a0aec0",
            "Agree": "#ed8936",
            "Strongly agree": "#c05621",
        },
        **draw_likert_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist likert chart

# %%
# parameters

persist_likert_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_likert = (
    persist_text.handle_errors(task_instance_id="persist_likert")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=draw_likert_chart,
        filename="elephants_relationship_likert.html",
        **persist_likert_params,
    )
    .call()
)


# %% [markdown]
# ## Filter effective / not effective df

# %%
# parameters

filter_eff_noeff_params = dict(
    errors=...,
)

# %%
# call the task


filter_eff_noeff = (
    filter_cols_df.handle_errors(task_instance_id="filter_eff_noeff")
    .partial(
        df=bin_survey_cols,
        cols=[
            "Effectiveness rating of primary crop protection method",
            "Effectiveness rating of that practice",
            "Effectiveness rating of water protection",
        ],
        **filter_eff_noeff_params,
    )
    .call()
)


# %% [markdown]
# ## Draw likert chart

# %%
# parameters

draw_likert_eff_params = dict(
    title=...,
    height_per_question=...,
    min_height=...,
    width=...,
    show_percentages=...,
    sort_questions=...,
    sort_by=...,
)

# %%
# call the task


draw_likert_eff = (
    create_likert_chart.handle_errors(task_instance_id="draw_likert_eff")
    .partial(
        df=filter_eff_noeff,
        response_order=["Not effective", "Effective", "Highly effective"],
        neutral_categories=["I don't know"],
        colors={
            "Not effective": "#D64545",
            "I don't know": "#A8A8A8",
            "Unspecified": "#D4D4D4",
            "Effective": "#2A9D8F",
            "Highly effective": "#2E7D32",
        },
        **draw_likert_eff_params,
    )
    .call()
)


# %% [markdown]
# ## Persist likert effective-not-effective chart

# %%
# parameters

persist_likert_eff_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_likert_eff = (
    persist_text.handle_errors(task_instance_id="persist_likert_eff")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=draw_likert_eff,
        filename="effectiveness_mitigation_methods.html",
        **persist_likert_eff_params,
    )
    .call()
)


# %% [markdown]
# ## Draw survey pie charts and persist

# %%
# parameters

draw_survey_pies_params = dict()

# %%
# call the task


draw_survey_pies = (
    draw_pie_and_persist.handle_errors(task_instance_id="draw_survey_pies")
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        df=bin_survey_cols,
        columns=[
            "Participant gender",
            "Female elephants live in family groups",
            "Female elephants protect their young",
            "Participant age group",
            "See more elephants now than before",
            "Do you change routes or schedules because of elephants",
            "What do you do when you encounter elephants on foot",
            "Noticed signs of illness in wild animals",
            "Willingness to join future community dialogue",
            "Use measures to protect crops from elephants",
            "Ever been involved in or witnessed an elephant harmed",
            "Elephants can smell and hear from far away",
            "Elephants move seasonally for food and water",
            "Elephant may shake its head when annoyed",
            "Elephant signals awareness by raising trunk",
            "Male elephants with secretions may be more aggressive",
            "Highest level of education",
            "Use measures to protect livestock from elephants",
            "Protect water sources from elephants",
            "Marital status",
            "Greatest threat to your livestock",
            "Benefit from the KCCDT Big Life electric fence",
            "Pay into fence maintenance fund",
            "Do you report elephant conflict incidents",
            "Which intervention would help you in future",
            "Opinion on having elephants in the area",
        ],
        **draw_survey_pies_params,
    )
    .call()
)


# %% [markdown]
# ## Draw survey bar charts and persist

# %%
# parameters

draw_survey_bar_params = dict()

# %%
# call the task


draw_survey_bar = (
    draw_bar_and_persist.handle_errors(task_instance_id="draw_survey_bar")
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        df=bin_survey_cols,
        columns=[
            "Participant tribe",
            "Years living in area",
            "Overall feelings about wildlife",
            "How often seen elephants in the last year",
            "Reaction to hearing about elephants being harmed",
            "Land tenure",
            "Greatest threat to crop production",
            "Household size bins",
            "Participant age bins",
        ],
        **draw_survey_bar_params,
    )
    .call()
)


# %% [markdown]
# ## Filter attitude score columns

# %%
# parameters

filter_attitude_cols_params = dict(
    errors=...,
)

# %%
# call the task


filter_attitude_cols = (
    filter_cols_df.handle_errors(task_instance_id="filter_attitude_cols")
    .partial(
        df=convt_to_int,
        cols=[
            "id",
            "geometry",
            "Humans and elephants can live together",
            "Importance of elephants living here",
            "Elephants should only live inside parks",
            "Elephants harm community members",
            "Elephants negatively affect my livelihood",
            "Elephants impact my emotional wellbeing",
            "Benefit from enjoying seeing elephants",
            "Elephants are important for a healthy ecosystem",
            "Acceptable to harm elephants if they damage property or livestock",
            "Acceptable to harm elephants if people are hurt",
            "Receive livelihood benefits from elephants",
        ],
        **filter_attitude_cols_params,
    )
    .call()
)


# %% [markdown]
# ## Calculate elephant sentiment scores

# %%
# parameters

calc_attitude_scores_params = dict()

# %%
# call the task


calc_attitude_scores = (
    calculate_elephant_sentiment_score.handle_errors(
        task_instance_id="calc_attitude_scores"
    )
    .partial(
        df=filter_attitude_cols,
        positive_columns=[
            "Humans and elephants can live together",
            "Importance of elephants living here",
            "Benefit from enjoying seeing elephants",
            "Elephants are important for a healthy ecosystem",
            "Receive livelihood benefits from elephants",
        ],
        negative_columns=[
            "Elephants should only live inside parks",
            "Elephants harm community members",
            "Elephants negatively affect my livelihood",
            "Elephants impact my emotional wellbeing",
            "Acceptable to harm elephants if they damage property or livestock",
            "Acceptable to harm elephants if people are hurt",
        ],
        **calc_attitude_scores_params,
    )
    .call()
)


# %% [markdown]
# ## Persist attitude scores df

# %%
# parameters

persist_attitude_df_params = dict(
    filetype=...,
)

# %%
# call the task


persist_attitude_df = (
    persist_df.handle_errors(task_instance_id="persist_attitude_df")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        df=calc_attitude_scores,
        filename="elephant_sentiment_scores",
        **persist_attitude_df_params,
    )
    .call()
)


# %% [markdown]
# ## Filter stat relevant questions

# %%
# parameters

filter_stat_qs_params = dict(
    errors=...,
)

# %%
# call the task


filter_stat_qs = (
    filter_cols_df.handle_errors(task_instance_id="filter_stat_qs")
    .partial(
        df=bin_survey_cols,
        cols=[
            "id",
            "Participant age",
            "Marital status",
            "Highest level of education",
            "Participant tribe",
            "Household size",
            "Participant age group",
            "Participant gender",
        ],
        **filter_stat_qs_params,
    )
    .call()
)


# %% [markdown]
# ## Merge stat and elephant attitude scores df

# %%
# parameters

merge_stat_ele_params = dict()

# %%
# call the task


merge_stat_ele = (
    merge_dataframes.handle_errors(task_instance_id="merge_stat_ele")
    .partial(
        left_df=filter_stat_qs,
        right_df=calc_attitude_scores,
        on="id",
        how="left",
        **merge_stat_ele_params,
    )
    .call()
)


# %% [markdown]
# ## Map stats df

# %%
# parameters

map_stats_df_params = dict()

# %%
# call the task


map_stats_df = (
    map_columns.handle_errors(task_instance_id="map_stats_df")
    .partial(
        df=merge_stat_ele,
        drop_columns=[],
        retain_columns=[],
        rename_columns={
            "id": "id",
            "Participant age": "age",
            "Marital status": "marital_status",
            "Highest level of education": "education_level",
            "Participant tribe": "tribe",
            "Household size": "household_size",
            "Participant age group": "age_group_distribution",
            "Participant gender": "gender_of_participant",
        },
        **map_stats_df_params,
    )
    .call()
)


# %% [markdown]
# ## Perform anova analysis and persist

# %%
# parameters

perform_anova_params = dict()

# %%
# call the task


perform_anova = (
    perform_anova_analysis.handle_errors(task_instance_id="perform_anova")
    .partial(
        dataframe=map_stats_df,
        target_column="elephant_sentiment_score",
        factor_columns=[
            "gender_of_participant",
            "age_group_distribution",
            "education_level",
            "marital_status",
        ],
        anova_type=2,
        **perform_anova_params,
    )
    .call()
)


# %% [markdown]
# ## Persist anova df to disk

# %%
# parameters

persist_anova_df_params = dict(
    filetype=...,
)

# %%
# call the task


persist_anova_df = (
    persist_df.handle_errors(task_instance_id="persist_anova_df")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        df=perform_anova,
        filename="anova_results",
        **persist_anova_df_params,
    )
    .call()
)


# %% [markdown]
# ## Draw boxplots and persist

# %%
# parameters

draw_stat_box_params = dict()

# %%
# call the task


draw_stat_box = (
    draw_boxplot_and_persist.handle_errors(task_instance_id="draw_stat_box")
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        df=map_stats_df,
        columns=[
            "marital_status",
            "education_level",
            "tribe",
            "age_group_distribution",
            "gender_of_participant",
        ],
        y_column="elephant_sentiment_score",
        **draw_stat_box_params,
    )
    .call()
)


# %% [markdown]
# ## Draw OLS scatterplot and persist

# %%
# parameters

draw_ols_plots_params = dict()

# %%
# call the task


draw_ols_plots = (
    draw_ols_scatterplot_and_persist.handle_errors(task_instance_id="draw_ols_plots")
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        df=map_stats_df,
        columns=["age", "household_size"],
        y_column="elephant_sentiment_score",
        **draw_ols_plots_params,
    )
    .call()
)


# %% [markdown]
# ## Draw tukey plots and persist

# %%
# parameters

draw_tukey_plots_params = dict()

# %%
# call the task


draw_tukey_plots = (
    draw_tukey_plots_and_persist.handle_errors(task_instance_id="draw_tukey_plots")
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        df=map_stats_df,
        columns=[
            "education_level",
            "age_group_distribution",
            "gender_of_participant",
            "marital_status",
        ],
        value_column="elephant_sentiment_score",
        **draw_tukey_plots_params,
    )
    .call()
)


# %% [markdown]
# ## Exclude geom outliers from df

# %%
# parameters

remove_geom_outliers_params = dict(
    z_threshold=...,
)

# %%
# call the task


remove_geom_outliers = (
    exclude_geom_outliers.handle_errors(task_instance_id="remove_geom_outliers")
    .partial(df=calc_attitude_scores, **remove_geom_outliers_params)
    .call()
)


# %% [markdown]
# ## Apply colormap to attitude scores df

# %%
# parameters

apply_att_colormap_params = dict()

# %%
# call the task


apply_att_colormap = (
    apply_color_map.handle_errors(task_instance_id="apply_att_colormap")
    .partial(
        input_column_name="overall_attitude",
        output_column_name="attitude_colors",
        colormap=["#FF0000", "#FFA500", "#FFFF00", "#00FF00", "#0000FF"],
        df=remove_geom_outliers,
        **apply_att_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Generate attitude score point layers

# %%
# parameters

generate_att_layers_params = dict(
    zoom=...,
)

# %%
# call the task


generate_att_layers = (
    create_point_layer.handle_errors(task_instance_id="generate_att_layers")
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={"fill_color_column": "attitude_colors"},
        legend={"label_column": "overall_attitude", "color_column": "attitude_colors"},
        tooltip_columns=[
            "overall_attitude",
            "attitude_colors",
            "elephant_sentiment_score",
        ],
        geodataframe=apply_att_colormap,
        **generate_att_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Combine map layers

# %%
# parameters

combine_att_map_layers_params = dict()

# %%
# call the task


combine_att_map_layers = (
    combine_map_layers.handle_errors(task_instance_id="combine_att_map_layers")
    .partial(
        static_layers=create_custom_map_layers,
        grouped_layers=generate_att_layers,
        **combine_att_map_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Zoom attitude point layers by view state

# %%
# parameters

zoom_att_layers_params = dict()

# %%
# call the task


zoom_att_layers = (
    create_view_state_from_gdf.handle_errors(task_instance_id="zoom_att_layers")
    .partial(pitch=0, bearing=0, gdf=apply_att_colormap, **zoom_att_layers_params)
    .call()
)


# %% [markdown]
# ## Draw attitude scores ecomap

# %%
# parameters

draw_att_ecomap_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_att_ecomap = (
    draw_ecomap.handle_errors(task_instance_id="draw_att_ecomap")
    .partial(
        tile_layers=configure_base_maps,
        north_arrow_style={"placement": "top-left"},
        legend_style={"placement": "bottom-right", "title": "Attitude Scores"},
        static=False,
        title=None,
        max_zoom=20,
        view_state=zoom_att_layers,
        geo_layers=combine_att_map_layers,
        **draw_att_ecomap_params,
    )
    .call()
)


# %% [markdown]
# ## Persist  attitude scores ecomap html paths

# %%
# parameters

persist_att_ecomap_urls_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_att_ecomap_urls = (
    persist_text.handle_errors(task_instance_id="persist_att_ecomap_urls")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=draw_att_ecomap,
        filename="attitude_scores_community.html",
        **persist_att_ecomap_urls_params,
    )
    .call()
)


# %% [markdown]
# ## Exclude geom outliers from df

# %%
# parameters

remove_geom_gn_outliers_params = dict(
    z_threshold=...,
)

# %%
# call the task


remove_geom_gn_outliers = (
    exclude_geom_outliers.handle_errors(task_instance_id="remove_geom_gn_outliers")
    .partial(df=bin_survey_cols, **remove_geom_gn_outliers_params)
    .call()
)


# %% [markdown]
# ## Apply colormap for gender distribution

# %%
# parameters

apply_gn_colormap_params = dict()

# %%
# call the task


apply_gn_colormap = (
    apply_color_map.handle_errors(task_instance_id="apply_gn_colormap")
    .partial(
        input_column_name="Participant gender",
        output_column_name="gender_colors",
        colormap=["#0000FF", "#FFC0CB", "#f8f8ff"],
        df=remove_geom_gn_outliers,
        **apply_gn_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Generate gender point layers

# %%
# parameters

generate_gn_layers_params = dict(
    zoom=...,
)

# %%
# call the task


generate_gn_layers = (
    create_point_layer.handle_errors(task_instance_id="generate_gn_layers")
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={"fill_color_column": "gender_colors"},
        legend={"label_column": "Participant gender", "color_column": "gender_colors"},
        tooltip_columns=["Participant gender", "gender_colors"],
        geodataframe=apply_gn_colormap,
        **generate_gn_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Combine  gender map layers

# %%
# parameters

combine_gn_map_layers_params = dict()

# %%
# call the task


combine_gn_map_layers = (
    combine_map_layers.handle_errors(task_instance_id="combine_gn_map_layers")
    .partial(
        static_layers=create_custom_map_layers,
        grouped_layers=generate_gn_layers,
        **combine_gn_map_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Zoom gender point layers by view state

# %%
# parameters

zoom_gn_layers_params = dict()

# %%
# call the task


zoom_gn_layers = (
    create_view_state_from_gdf.handle_errors(task_instance_id="zoom_gn_layers")
    .partial(pitch=0, bearing=0, gdf=apply_gn_colormap, **zoom_gn_layers_params)
    .call()
)


# %% [markdown]
# ## Draw gender scores ecomap

# %%
# parameters

draw_gn_ecomap_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_gn_ecomap = (
    draw_ecomap.handle_errors(task_instance_id="draw_gn_ecomap")
    .partial(
        tile_layers=configure_base_maps,
        north_arrow_style={"placement": "top-left"},
        legend_style={"placement": "bottom-right", "title": "Gender distribution"},
        static=False,
        title=None,
        max_zoom=20,
        view_state=zoom_gn_layers,
        geo_layers=combine_gn_map_layers,
        **draw_gn_ecomap_params,
    )
    .call()
)


# %% [markdown]
# ## Persist gender ecomap html paths

# %%
# parameters

persist_gn_ecomap_urls_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_gn_ecomap_urls = (
    persist_text.handle_errors(task_instance_id="persist_gn_ecomap_urls")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=draw_gn_ecomap,
        filename="gender_distribution_ecomap.html",
        **persist_gn_ecomap_urls_params,
    )
    .call()
)


# %% [markdown]
# ## Exclude geom outliers from df

# %%
# parameters

remove_geom_ov_outliers_params = dict(
    z_threshold=...,
)

# %%
# call the task


remove_geom_ov_outliers = (
    exclude_geom_outliers.handle_errors(task_instance_id="remove_geom_ov_outliers")
    .partial(df=bin_survey_cols, **remove_geom_ov_outliers_params)
    .call()
)


# %% [markdown]
# ## Apply colormap for overall survey

# %%
# parameters

apply_ov_colormap_params = dict()

# %%
# call the task


apply_ov_colormap = (
    apply_color_map.handle_errors(task_instance_id="apply_ov_colormap")
    .partial(
        input_column_name="event_type",
        output_column_name="event_type_colors",
        colormap=["#C70039"],
        df=remove_geom_ov_outliers,
        **apply_ov_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Generate overall point layers

# %%
# parameters

generate_ov_layers_params = dict(
    tooltip_columns=...,
    zoom=...,
)

# %%
# call the task


generate_ov_layers = (
    create_point_layer.handle_errors(task_instance_id="generate_ov_layers")
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={"fill_color_column": "event_type_colors"},
        legend={"labels": ["Survey locations"], "colors": ["#C70039"]},
        geodataframe=apply_ov_colormap,
        **generate_ov_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Combine overall map layers

# %%
# parameters

combine_ov_map_layers_params = dict()

# %%
# call the task


combine_ov_map_layers = (
    combine_map_layers.handle_errors(task_instance_id="combine_ov_map_layers")
    .partial(
        static_layers=create_custom_map_layers,
        grouped_layers=generate_ov_layers,
        **combine_ov_map_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Zoom overall point layers by view state

# %%
# parameters

zoom_ov_layers_params = dict()

# %%
# call the task


zoom_ov_layers = (
    create_view_state_from_gdf.handle_errors(task_instance_id="zoom_ov_layers")
    .partial(pitch=0, bearing=0, gdf=apply_ov_colormap, **zoom_ov_layers_params)
    .call()
)


# %% [markdown]
# ## Draw overall ecomap

# %%
# parameters

draw_ov_ecomap_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_ov_ecomap = (
    draw_ecomap.handle_errors(task_instance_id="draw_ov_ecomap")
    .partial(
        tile_layers=configure_base_maps,
        north_arrow_style={"placement": "top-left"},
        legend_style={"placement": "bottom-right", "title": "Legend"},
        static=False,
        title=None,
        max_zoom=20,
        view_state=zoom_ov_layers,
        geo_layers=combine_ov_map_layers,
        **draw_ov_ecomap_params,
    )
    .call()
)


# %% [markdown]
# ## Persist overall  ecomap html paths

# %%
# parameters

persist_ov_ecomap_urls_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_ov_ecomap_urls = (
    persist_text.handle_errors(task_instance_id="persist_ov_ecomap_urls")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=draw_ov_ecomap,
        filename="survey_locations_ecomap.html",
        **persist_ov_ecomap_urls_params,
    )
    .call()
)


# %% [markdown]
# ## Convert  pie chart html to png

# %%
# parameters

convt_pie_html_png_params = dict()

# %%
# call the task


convt_pie_html_png = (
    zhtml_to_png.handle_errors(task_instance_id="convt_pie_html_png")
    .partial(
        html_path=draw_survey_pies,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"wait_for_timeout": 100},
        **convt_pie_html_png_params,
    )
    .call()
)


# %% [markdown]
# ## Convert bar chart html to png

# %%
# parameters

convt_bar_html_png_params = dict()

# %%
# call the task


convt_bar_html_png = (
    zhtml_to_png.handle_errors(task_instance_id="convt_bar_html_png")
    .partial(
        html_path=draw_survey_bar,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"wait_for_timeout": 100},
        **convt_bar_html_png_params,
    )
    .call()
)


# %% [markdown]
# ## Convert stats html to png

# %%
# parameters

convt_stats_html_png_params = dict()

# %%
# call the task


convt_stats_html_png = (
    zhtml_to_png.handle_errors(task_instance_id="convt_stats_html_png")
    .partial(
        html_path=draw_stat_box,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"wait_for_timeout": 100},
        **convt_stats_html_png_params,
    )
    .call()
)


# %% [markdown]
# ## Convert  ols html to png

# %%
# parameters

convt_ols_html_png_params = dict()

# %%
# call the task


convt_ols_html_png = (
    zhtml_to_png.handle_errors(task_instance_id="convt_ols_html_png")
    .partial(
        html_path=draw_ols_plots,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"wait_for_timeout": 100},
        **convt_ols_html_png_params,
    )
    .call()
)


# %% [markdown]
# ## Convert tukey html to png

# %%
# parameters

convt_tuk_html_png_params = dict()

# %%
# call the task


convt_tuk_html_png = (
    zhtml_to_png.handle_errors(task_instance_id="convt_tuk_html_png")
    .partial(
        html_path=draw_tukey_plots,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"wait_for_timeout": 100},
        **convt_tuk_html_png_params,
    )
    .call()
)


# %% [markdown]
# ## Convert ecomap html to png

# %%
# parameters

convt_ecohtml_png_params = dict()

# %%
# call the task


convt_ecohtml_png = (
    zhtml_to_png.handle_errors(task_instance_id="convt_ecohtml_png")
    .partial(
        html_path=[
            persist_att_ecomap_urls,
            persist_gn_ecomap_urls,
            persist_ov_ecomap_urls,
            persist_likert,
            persist_likert_eff,
        ],
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"wait_for_timeout": 20000},
        **convt_ecohtml_png_params,
    )
    .call()
)


# %% [markdown]
# ## Create survey dashboard

# %%
# parameters

survey_dashboard_params = dict()

# %%
# call the task


survey_dashboard = (
    gather_dashboard.handle_errors(task_instance_id="survey_dashboard")
    .partial(
        details=workflow_details,
        widgets=[],
        time_range=time_range,
        groupers=groupers,
        **survey_dashboard_params,
    )
    .call()
)
