# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.tasks.config import set_workflow_details
from ecoscope_workflows_core.tasks.filter import set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers
from ecoscope_workflows_core.tasks.io import persist_text, set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view,
    gather_dashboard,
    merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped,
    any_is_empty_df,
    never,
)
from ecoscope_workflows_core.tasks.transformation import map_columns
from ecoscope_workflows_ext_ate.tasks import (
    bin_columns,
    calculate_elephant_sentiment_score,
    convert_object_to_value,
    convert_to_int,
    create_likert_chart,
    create_view_state_from_gdf,
    download_file_and_persist,
    draw_boxplot_and_persist,
    draw_ols_scatterplot_and_persist,
    draw_pie_and_persist,
    draw_tukey_plots_and_persist,
    fill_missing_values,
    filter_cols_df,
    format_demographic_table,
    map_survey_columns,
    map_survey_responses,
    merge_dataframes,
    perform_anova_analysis,
    view_df,
    zhtml_to_png,
    zip_grouped_by_key,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events, persist_df
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_point_layer,
    draw_ecomap,
    set_base_maps,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map,
    normalize_column,
)

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .handle_errors(task_instance_id="workflow_details")
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .handle_errors(task_instance_id="time_range")
        .partial(
            time_format="%d %b %Y %H:%M:%S %Z", **(params_dict.get("time_range") or {})
        )
        .call()
    )

    groupers = (
        set_groupers.validate()
        .handle_errors(task_instance_id="groupers")
        .partial(**(params_dict.get("groupers") or {}))
        .call()
    )

    er_client_name = (
        set_er_connection.validate()
        .handle_errors(task_instance_id="er_client_name")
        .partial(**(params_dict.get("er_client_name") or {}))
        .call()
    )

    configure_base_maps = (
        set_base_maps.validate()
        .handle_errors(task_instance_id="configure_base_maps")
        .partial(**(params_dict.get("configure_base_maps") or {}))
        .call()
    )

    download_ate_tpt = (
        download_file_and_persist.validate()
        .handle_errors(task_instance_id="download_ate_tpt")
        .partial(
            url="https://www.dropbox.com/scl/fi/8eig0iyg2uu76eghi2sd4/ate_survey_template.docx?rlkey=pe5dpqnskj60v0b5uchocdpy1&st=zdokeegg&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            **(params_dict.get("download_ate_tpt") or {}),
        )
        .call()
    )

    get_survey_events_data = (
        get_events.validate()
        .handle_errors(task_instance_id="get_survey_events_data")
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "reported_by",
                "serial_number",
                "geometry",
                "created_at",
                "event_details",
            ],
            event_types=["atequestionnaire_rep"],
            raise_on_empty=False,
            include_details=True,
            include_updates=False,
            include_related_events=False,
            **(params_dict.get("get_survey_events_data") or {}),
        )
        .call()
    )

    normalize_event_details = (
        normalize_column.validate()
        .handle_errors(task_instance_id="normalize_event_details")
        .partial(
            column="event_details",
            df=get_survey_events_data,
            **(params_dict.get("normalize_event_details") or {}),
        )
        .call()
    )

    rename_survey_columns = (
        map_columns.validate()
        .handle_errors(task_instance_id="rename_survey_columns")
        .partial(
            df=normalize_event_details,
            drop_columns=[
                "event_type",
                "event_category",
                "reported_by",
                "event_details__updates",
                "event_details__end_time",
                "event_details__closing_statement",
                "event_details__participant_occupationifother",
                "event_details__livestock_health_1_otheranimals",
                "event_details__livestock_health_3_otheranimals",
                "event_details__participant_tribeifother",
                "event_details__participant_land_tenureifother",
                "event_details__behaviour_2",
                "event_details__behaviour_4_ifyes",
                "event_details__one_health_7",
                "event_details__livestock_health_4",
                "event_details__livestock_health_5",
                "event_details__livestock_health_6",
                "event_details__behaviour_killing_2",
                "event_details__behaviour_killing_3",
                "event_details__perception_challenges",
                "event_details__participant_occupation",
                "event_details__water_mitigation_use_2",
                "event_details__livestock_health_3_cattle",
                "event_details__livestock_health_3_donkies",
                "event_details__livestock_health_3_sheepgoat",
                "event_details__perception_conservation_interventions_6",
                "event_details__perception_conservation_interventions_4ifyes",
                "event_details__perception_conservation_interventions_2_ifnowhy",
                "event_details__belief_costs_4",
                "event_details__belief_benefits_4",
                "event_details__crop_mitigation_2",
                "event_details__perception_crop_production_threatsifother",
                "event_details__perception_conservation_interventions_5ifother",
                "event_details__one_health_8_ifyes",
                "event_details__participant_tribeifother",
                "event_details__participant_land_tenureifother",
                "event_details__livestock_health_3_dogs",
            ],
            retain_columns=[],
            rename_columns={
                "event_details__participant_age": "Participant age",
                "event_details__participant_tribe": "Participant tribe",
                "event_details__participant_gender": "Participant gender",
                "event_details__elephant_knowledge_1": "Female elephants live in family groups",
                "event_details__elephant_knowledge_2": "Female elephants protect their young",
                "event_details__participant_num_cows": "Number of cows",
                "event_details__participant_age_range": "Participant age group",
                "event_details__participant_agreement": "Respondent agreed to interview",
                "event_details__participant_household": "Household size",
                "event_details__participant_land_owned": "Land owned (acres)",
                "event_details__participant_num_shoats": "Number of shoats",
                "event_details__participant_agricultural_land": "Agricultural land (acres)",
                "event_details__participant_duration_in_amboseli": "Years living in area",
                "event_details__belief_1": "Humans and elephants can live together",
                "event_details__attitude_0": "Overall feelings about wildlife",
                "event_details__attitude_1": "Opinion on having elephants in the area",
                "event_details__attitude_2": "Importance of elephants living here",
                "event_details__attitude_3": "Elephants should only live inside parks",
                "event_details__exposure_1": "How often seen elephants in the last year",
                "event_details__exposure_2": "See more elephants now than before",
                "event_details__behaviour_1": "Do you change routes or schedules because of elephants",
                "event_details__behaviour_3": "Effectiveness rating of that practice",
                "event_details__behaviour_4": "What do you do when you encounter elephants on foot",
                "event_details__one_health_8": "Noticed signs of illness in wild animals",
                "event_details__belief_costs_1": "Elephants harm community members",
                "event_details__belief_costs_2": "Elephants negatively affect my livelihood",
                "event_details__belief_costs_3": "Elephants impact my emotional wellbeing",
                "event_details__future_activity": "Willingness to join future community dialogue",
                "event_details__attitude_killing": "Reaction to hearing about elephants being harmed",
                "event_details__belief_benefits_1": "Receive livelihood benefits from elephants",
                "event_details__belief_benefits_2": "Benefit from enjoying seeing elephants",
                "event_details__belief_benefits_3": "Elephants are important for a healthy ecosystem",
                "event_details__crop_mitigation_1": "Use measures to protect crops from elephants",
                "event_details__behaviour_killing_1": "Ever been involved in or witnessed an elephant harmed",
                "event_details__hazard_acceptance_1": "Acceptable to harm elephants if they damage property or livestock",
                "event_details__hazard_acceptance_2": "Acceptable to harm elephants if people are hurt",
                "event_details__elephant_knowledge_3": "Elephants can smell and hear from far away",
                "event_details__elephant_knowledge_4": "Elephants move seasonally for food and water",
                "event_details__elephant_knowledge_6": "Elephant may shake its head when annoyed",
                "event_details__elephant_knowledge_7": "Elephant signals awareness by raising trunk",
                "event_details__elephant_knowledge_8": "Male elephants with secretions may be more aggressive",
                "event_details__participant_education": "Highest level of education",
                "event_details__livestock_mitigation_1": "Use measures to protect livestock from elephants",
                "event_details__water_mitigation_use_1": "Protect water sources from elephants",
                "event_details__water_mitigation_use_3": "Effectiveness rating of water protection",
                "event_details__livestock_health_1_dogs": "Number of dogs",
                "event_details__participant_land_tenure": "Land tenure",
                "event_details__livestock_health_1_cattle": "Number of cattle",
                "event_details__livestock_health_1_donkies": "Number of donkeys",
                "event_details__participant_marital_status": "Marital status",
                "event_details__livestock_health_1_sheepgoat": "Number of sheep or goats",
                "event_details__perception_livestock_threats": "Greatest threat to your livestock",
                "event_details__perception_crop_production_threats": "Greatest threat to crop production",
                "event_details__perception_conservation_interventions_1": "Benefit from the KCCDT Big Life electric fence",
                "event_details__perception_conservation_interventions_2": "Pay into fence maintenance fund",
                "event_details__perception_conservation_interventions_4": "Do you report elephant conflict incidents",
                "event_details__perception_conservation_interventions_5": "Which intervention would help you in future",
                "event_details__crop_mitigation_3": "Effectiveness rating of primary crop protection method",
                "event_details__livestock_mitigation_2": "If yes, which methods do you use for livestock",
            },
            **(params_dict.get("rename_survey_columns") or {}),
        )
        .call()
    )

    convert_obj_to_num = (
        convert_object_to_value.validate()
        .handle_errors(task_instance_id="convert_obj_to_num")
        .partial(
            df=rename_survey_columns,
            columns=[
                "Participant age",
                "Number of cows",
                "Household size",
                "Land owned (acres)",
                "Number of shoats",
                "Agricultural land (acres)",
                "Number of sheep or goats",
                "Number of dogs",
                "Number of cattle",
                "Number of donkeys",
            ],
            **(params_dict.get("convert_obj_to_num") or {}),
        )
        .call()
    )

    convert_obj_to_str = (
        convert_object_to_value.validate()
        .handle_errors(task_instance_id="convert_obj_to_str")
        .partial(
            df=convert_obj_to_num,
            columns=[
                "id",
                "Participant tribe",
                "Participant gender",
                "Female elephants live in family groups",
                "Female elephants protect their young",
                "Participant age group",
                "Respondent agreed to interview",
                "Years living in area",
                "Humans and elephants can live together",
                "Overall feelings about wildlife",
                "Opinion on having elephants in the area",
                "Importance of elephants living here",
                "Elephants should only live inside parks",
                "How often seen elephants in the last year",
                "See more elephants now than before",
                "Do you change routes or schedules because of elephants",
                "Effectiveness rating of that practice",
                "What do you do when you encounter elephants on foot",
                "Noticed signs of illness in wild animals",
                "Elephants harm community members",
                "Elephants negatively affect my livelihood",
                "Elephants impact my emotional wellbeing",
                "Willingness to join future community dialogue",
                "Reaction to hearing about elephants being harmed",
                "Receive livelihood benefits from elephants",
                "Benefit from enjoying seeing elephants",
                "Elephants are important for a healthy ecosystem",
                "Use measures to protect crops from elephants",
                "Ever been involved in or witnessed an elephant harmed",
                "Acceptable to harm elephants if they damage property or livestock",
                "Acceptable to harm elephants if people are hurt",
                "Elephants can smell and hear from far away",
                "Elephants move seasonally for food and water",
                "Elephant may shake its head when annoyed",
                "Elephant signals awareness by raising trunk",
                "Male elephants with secretions may be more aggressive",
                "Highest level of education",
                "Use measures to protect livestock from elephants",
                "Protect water sources from elephants",
                "Effectiveness rating of water protection",
                "Land tenure",
                "Marital status",
                "Greatest threat to your livestock",
                "Greatest threat to crop production",
                "Benefit from the KCCDT Big Life electric fence",
                "Pay into fence maintenance fund",
                "Do you report elephant conflict incidents",
                "Which intervention would help you in future",
                "Effectiveness rating of primary crop protection method",
                "If yes, which methods do you use for livestock",
            ],
            **(params_dict.get("convert_obj_to_str") or {}),
        )
        .call()
    )

    fill_values = (
        fill_missing_values.validate()
        .handle_errors(task_instance_id="fill_values")
        .partial(
            dataframe=convert_obj_to_str,
            numeric_fill_value=0,
            categorical_fill_value="Unspecified",
            numeric_columns=[
                "Participant age",
                "Number of cows",
                "Household size",
                "Land owned (acres)",
                "Number of shoats",
                "Agricultural land (acres)",
                "Number of sheep or goats",
                "Number of dogs",
                "Number of cattle",
                "Number of donkeys",
            ],
            categorical_columns=[
                "id",
                "Participant tribe",
                "Participant gender",
                "Female elephants live in family groups",
                "Female elephants protect their young",
                "Participant age group",
                "Respondent agreed to interview",
                "Years living in area",
                "Humans and elephants can live together",
                "Overall feelings about wildlife",
                "Opinion on having elephants in the area",
                "Importance of elephants living here",
                "Elephants should only live inside parks",
                "How often seen elephants in the last year",
                "See more elephants now than before",
                "Do you change routes or schedules because of elephants",
                "Effectiveness rating of that practice",
                "What do you do when you encounter elephants on foot",
                "Noticed signs of illness in wild animals",
                "Elephants harm community members",
                "Elephants negatively affect my livelihood",
                "Elephants impact my emotional wellbeing",
                "Willingness to join future community dialogue",
                "Reaction to hearing about elephants being harmed",
                "Receive livelihood benefits from elephants",
                "Benefit from enjoying seeing elephants",
                "Elephants are important for a healthy ecosystem",
                "Use measures to protect crops from elephants",
                "Ever been involved in or witnessed an elephant harmed",
                "Acceptable to harm elephants if they damage property or livestock",
                "Acceptable to harm elephants if people are hurt",
                "Elephants can smell and hear from far away",
                "Elephants move seasonally for food and water",
                "Elephant may shake its head when annoyed",
                "Elephant signals awareness by raising trunk",
                "Male elephants with secretions may be more aggressive",
                "Highest level of education",
                "Use measures to protect livestock from elephants",
                "Protect water sources from elephants",
                "Effectiveness rating of water protection",
                "Land tenure",
                "Marital status",
                "Greatest threat to your livestock",
                "Greatest threat to crop production",
                "Benefit from the KCCDT Big Life electric fence",
                "Pay into fence maintenance fund",
                "Do you report elephant conflict incidents",
                "Which intervention would help you in future",
                "Effectiveness rating of primary crop protection method",
                "If yes, which methods do you use for livestock",
            ],
            **(params_dict.get("fill_values") or {}),
        )
        .call()
    )

    map_agree_disagree = (
        map_survey_responses.validate()
        .handle_errors(task_instance_id="map_agree_disagree")
        .partial(
            df=fill_values,
            columns=[
                "Humans and elephants can live together",
                "Importance of elephants living here",
                "Elephants should only live inside parks",
                "Elephants harm community members",
                "Elephants negatively affect my livelihood",
                "Elephants impact my emotional wellbeing",
                "Benefit from enjoying seeing elephants",
                "Elephants are important for a healthy ecosystem",
                "Acceptable to harm elephants if they damage property or livestock",
                "Acceptable to harm elephants if people are hurt",
                "Receive livelihood benefits from elephants",
            ],
            value_map={
                "strongly_agree": "Strongly agree",
                "agree": "Agree",
                "neutral": "Neutral",
                "disagree": "Disagree",
                "strongly_disagree": "Strongly disagree",
                "i_dont_know": "I don't know",
                "prefer_not_to_answer": "Prefer not to answer",
            },
            **(params_dict.get("map_agree_disagree") or {}),
        )
        .call()
    )

    map_yes_no = (
        map_survey_responses.validate()
        .handle_errors(task_instance_id="map_yes_no")
        .partial(
            df=map_agree_disagree,
            columns=[
                "Humans and elephants can live together",
                "Importance of elephants living here",
                "Elephants should only live inside parks",
                "Elephants harm community members",
                "Elephants negatively affect my livelihood",
                "Elephants impact my emotional wellbeing",
                "Benefit from enjoying seeing elephants",
                "Elephants are important for a healthy ecosystem",
                "Acceptable to harm elephants if they damage property or livestock",
                "Acceptable to harm elephants if people are hurt",
                "Receive livelihood benefits from elephants",
            ],
            value_map={
                "yes": "Yes",
                "no": "No",
                "i_dont_know": "I don't know",
                "prefer_not_to_answer": "Prefer not to answer",
            },
            **(params_dict.get("map_yes_no") or {}),
        )
        .call()
    )

    map_col_surveys = (
        map_survey_columns.validate()
        .handle_errors(task_instance_id="map_col_surveys")
        .partial(
            df=map_yes_no,
            cols=[
                "Female elephants live in family groups",
                "Female elephants protect their young",
                "Elephants move seasonally for food and water",
                "Elephant may shake its head when annoyed",
                "Elephant signals awareness by raising trunk",
                "Male elephants with secretions may be more aggressive",
                "Elephants can smell and hear from far away",
                "Effectiveness rating of primary crop protection method",
                "Effectiveness rating of that practice",
                "Effectiveness rating of water protection",
                "Participant age",
                "Household size",
                "Participant tribe",
                "Participant gender",
                "Participant age group",
                "Years living in area",
                "Overall feelings about wildlife",
                "Opinion on having elephants in the area",
                "How often seen elephants in the last year",
                "What do you do when you encounter elephants on foot",
                "Reaction to hearing about elephants being harmed",
                "Highest level of education",
                "Greatest threat to your livestock",
                "Greatest threat to crop production",
                "Which intervention would help you in future",
                "Marital status",
                "Land tenure",
            ],
            **(params_dict.get("map_col_surveys") or {}),
        )
        .call()
    )

    print_mapped_df = (
        view_df.validate()
        .handle_errors(task_instance_id="print_mapped_df")
        .partial(
            gdf=map_col_surveys,
            name="View presently mapped df",
            **(params_dict.get("print_mapped_df") or {}),
        )
        .call()
    )

    convt_to_int = (
        convert_to_int.validate()
        .handle_errors(task_instance_id="convt_to_int")
        .partial(
            df=map_col_surveys,
            columns=[
                "Participant age",
                "Number of cows",
                "Household size",
                "Number of shoats",
                "Agricultural land (acres)",
                "Number of sheep or goats",
                "Number of dogs",
                "Number of cattle",
                "Number of donkeys",
            ],
            **(params_dict.get("convt_to_int") or {}),
        )
        .call()
    )

    create_demo_table = (
        format_demographic_table.validate()
        .handle_errors(task_instance_id="create_demo_table")
        .partial(
            df=convt_to_int,
            columns_of_interest=[
                "Participant gender",
                "Participant age",
                "Participant tribe",
                "Household size",
                "Highest level of education",
            ],
            **(params_dict.get("create_demo_table") or {}),
        )
        .call()
    )

    persist_demo_df = (
        persist_df.validate()
        .handle_errors(task_instance_id="persist_demo_df")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            df=create_demo_table,
            filename="demographic_table",
            **(params_dict.get("persist_demo_df") or {}),
        )
        .call()
    )

    bin_survey_cols = (
        bin_columns.validate()
        .handle_errors(task_instance_id="bin_survey_cols")
        .partial(
            df=convt_to_int,
            columns=[
                "Participant age",
                "Number of cows",
                "Household size",
                "Number of shoats",
                "Land owned (acres)",
                "Agricultural land (acres)",
                "Number of dogs",
                "Number of cattle",
                "Number of donkeys",
                "Number of sheep or goats",
            ],
            **(params_dict.get("bin_survey_cols") or {}),
        )
        .call()
    )

    filter_elephant_qs = (
        filter_cols_df.validate()
        .handle_errors(task_instance_id="filter_elephant_qs")
        .partial(
            df=bin_survey_cols,
            cols=[
                "Humans and elephants can live together",
                "Importance of elephants living here",
                "Elephants should only live inside parks",
                "Elephants harm community members",
                "Elephants negatively affect my livelihood",
                "Elephants impact my emotional wellbeing",
                "Benefit from enjoying seeing elephants",
                "Elephants are important for a healthy ecosystem",
                "Acceptable to harm elephants if they damage property or livestock",
                "Acceptable to harm elephants if people are hurt",
                "Receive livelihood benefits from elephants",
            ],
            **(params_dict.get("filter_elephant_qs") or {}),
        )
        .call()
    )

    draw_likert_chart = (
        create_likert_chart.validate()
        .handle_errors(task_instance_id="draw_likert_chart")
        .partial(
            df=filter_elephant_qs,
            response_order=[
                "Strongly disagree",
                "Disagree",
                "Neutral",
                "Agree",
                "Strongly agree",
            ],
            neutral_categories=["Neutral", "I don't know", "Unspecified"],
            colors={
                "Strongly disagree": "#2c5282",
                "Disagree": "#4299e1",
                "Neutral": "#a0aec0",
                "Unspecified": "#a0aec0",
                "I don't know": "#a0aec0",
                "Agree": "#ed8936",
                "Strongly agree": "#c05621",
            },
            **(params_dict.get("draw_likert_chart") or {}),
        )
        .call()
    )

    persist_likert = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_likert")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_likert_chart,
            filename="elephants_relationship_likert",
            **(params_dict.get("persist_likert") or {}),
        )
        .call()
    )

    filter_eff_noeff = (
        filter_cols_df.validate()
        .handle_errors(task_instance_id="filter_eff_noeff")
        .partial(
            df=bin_survey_cols,
            cols=[
                "Effectiveness rating of primary crop protection method",
                "Effectiveness rating of that practice",
                "Effectiveness rating of water protection",
            ],
            **(params_dict.get("filter_eff_noeff") or {}),
        )
        .call()
    )

    draw_likert_eff = (
        create_likert_chart.validate()
        .handle_errors(task_instance_id="draw_likert_eff")
        .partial(
            df=filter_eff_noeff,
            response_order=["Not effective", "Effective", "Highly effective"],
            neutral_categories=["I don't know", "Unspecified"],
            colors={
                "Not effective": "#D64545",
                "I don't know": "#A8A8A8",
                "Unspecified": "#D4D4D4",
                "Effective": "#2A9D8F",
                "Highly effective": "#2E7D32",
            },
            **(params_dict.get("draw_likert_eff") or {}),
        )
        .call()
    )

    persist_likert_eff = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_likert_eff")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_likert_eff,
            filename="effectiveness_mitigation_methods",
            **(params_dict.get("persist_likert_eff") or {}),
        )
        .call()
    )

    draw_survey_pies = (
        draw_pie_and_persist.validate()
        .handle_errors(task_instance_id="draw_survey_pies")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            df=bin_survey_cols,
            columns=[
                "Participant gender",
                "Female elephants live in family groups",
                "Female elephants protect their young",
                "Participant age group",
                "See more elephants now than before",
                "Do you change routes or schedules because of elephants",
                "What do you do when you encounter elephants on foot",
                "Noticed signs of illness in wild animals",
                "Willingness to join future community dialogue",
                "Use measures to protect crops from elephants",
                "Ever been involved in or witnessed an elephant harmed",
                "Elephants can smell and hear from far away",
                "Elephants move seasonally for food and water",
                "Elephant may shake its head when annoyed",
                "Elephant signals awareness by raising trunk",
                "Male elephants with secretions may be more aggressive",
                "Highest level of education",
                "Use measures to protect livestock from elephants",
                "Protect water sources from elephants",
                "Marital status",
                "Greatest threat to your livestock",
                "Benefit from the KCCDT Big Life electric fence",
                "Pay into fence maintenance fund",
                "Do you report elephant conflict incidents",
                "Which intervention would help you in future",
                "Opinion on having elephants in the area",
            ],
            **(params_dict.get("draw_survey_pies") or {}),
        )
        .call()
    )

    draw_survey_bar = (
        draw_pie_and_persist.validate()
        .handle_errors(task_instance_id="draw_survey_bar")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            df=bin_survey_cols,
            columns=[
                "Participant tribe",
                "Years living in area",
                "Overall feelings about wildlife",
                "How often seen elephants in the last year",
                "Reaction to hearing about elephants being harmed",
                "Land tenure",
                "Greatest threat to crop production",
                "Household size bins",
                "Participant age bins",
            ],
            **(params_dict.get("draw_survey_bar") or {}),
        )
        .call()
    )

    filter_attitude_cols = (
        filter_cols_df.validate()
        .handle_errors(task_instance_id="filter_attitude_cols")
        .partial(
            df=bin_survey_cols,
            cols=[
                "id",
                "geometry",
                "Humans and elephants can live together",
                "Importance of elephants living here",
                "Elephants should only live inside parks",
                "Elephants harm community members",
                "Elephants negatively affect my livelihood",
                "Elephants impact my emotional wellbeing",
                "Benefit from enjoying seeing elephants",
                "Elephants are important for a healthy ecosystem",
                "Acceptable to harm elephants if they damage property or livestock",
                "Acceptable to harm elephants if people are hurt",
                "Receive livelihood benefits from elephants",
            ],
            **(params_dict.get("filter_attitude_cols") or {}),
        )
        .call()
    )

    calc_attitude_scores = (
        calculate_elephant_sentiment_score.validate()
        .handle_errors(task_instance_id="calc_attitude_scores")
        .partial(
            df=filter_attitude_cols,
            positive_columns=[
                "Humans and elephants can live together",
                "Importance of elephants living here",
                "Benefit from enjoying seeing elephants",
                "Elephants are important for a healthy ecosystem",
                "Receive livelihood benefits from elephants",
            ],
            negative_columns=[
                "Elephants should only live inside parks",
                "Elephants harm community members",
                "Elephants negatively affect my livelihood",
                "Elephants impact my emotional wellbeing",
                "Acceptable to harm elephants if they damage property or livestock",
                "Acceptable to harm elephants if people are hurt",
            ],
            **(params_dict.get("calc_attitude_scores") or {}),
        )
        .call()
    )

    persist_attitude_df = (
        persist_df.validate()
        .handle_errors(task_instance_id="persist_attitude_df")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            df=calc_attitude_scores,
            **(params_dict.get("persist_attitude_df") or {}),
        )
        .call()
    )

    filter_stat_qs = (
        filter_cols_df.validate()
        .handle_errors(task_instance_id="filter_stat_qs")
        .partial(
            df=bin_survey_cols,
            cols=[
                "id",
                "Participant age",
                "Marital status",
                "Highest level of education",
                "Participant tribe",
                "Household size",
                "Participant age group",
                "Participant gender",
            ],
            **(params_dict.get("filter_stat_qs") or {}),
        )
        .call()
    )

    merge_stat_ele = (
        merge_dataframes.validate()
        .handle_errors(task_instance_id="merge_stat_ele")
        .partial(
            left_df=filter_stat_qs,
            right_df=calc_attitude_scores,
            on="id",
            how="left",
            **(params_dict.get("merge_stat_ele") or {}),
        )
        .call()
    )

    map_stats_df = (
        map_columns.validate()
        .handle_errors(task_instance_id="map_stats_df")
        .partial(
            df=merge_stat_ele,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "id": "id",
                "Participant age": "age",
                "Marital status": "marital_status",
                "Highest level of education": "education_level",
                "Participant tribe": "tribe",
                "Household size": "household_size",
                "Participant age group": "age_group",
                "Participant gender": "gender",
            },
            **(params_dict.get("map_stats_df") or {}),
        )
        .call()
    )

    perform_anova = (
        perform_anova_analysis.validate()
        .handle_errors(task_instance_id="perform_anova")
        .partial(
            dataframe=map_stats_df,
            target_column="elephant_sentiment_score",
            factor_columns=[
                "gender_of_participant",
                "age_group_distribution",
                "education_level",
                "marital_status",
            ],
            anova_type=2,
            **(params_dict.get("perform_anova") or {}),
        )
        .call()
    )

    persist_anova_df = (
        persist_df.validate()
        .handle_errors(task_instance_id="persist_anova_df")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            df=perform_anova,
            filename="anova_results",
            **(params_dict.get("persist_anova_df") or {}),
        )
        .call()
    )

    draw_stat_box = (
        draw_boxplot_and_persist.validate()
        .handle_errors(task_instance_id="draw_stat_box")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            df=map_stats_df,
            columns=[
                "marital_status",
                "education_level",
                "tribe",
                "age_group_distribution",
                "gender_of_participant",
            ],
            y_column="elephant_sentiment_score",
            **(params_dict.get("draw_stat_box") or {}),
        )
        .call()
    )

    draw_ols_plots = (
        draw_ols_scatterplot_and_persist.validate()
        .handle_errors(task_instance_id="draw_ols_plots")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            df=map_stats_df,
            columns=["age", "household_size"],
            y_column="elephant_sentiment_score",
            **(params_dict.get("draw_ols_plots") or {}),
        )
        .call()
    )

    draw_tukey_plots = (
        draw_tukey_plots_and_persist.validate()
        .handle_errors(task_instance_id="draw_tukey_plots")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            df=map_stats_df,
            columns=[
                "education_level",
                "age_group_distribution",
                "gender_of_participant",
                "marital_status",
            ],
            value_column="elephant_sentiment_score",
            **(params_dict.get("draw_tukey_plots") or {}),
        )
        .call()
    )

    apply_att_colormap = (
        apply_color_map.validate()
        .handle_errors(task_instance_id="apply_att_colormap")
        .partial(
            input_column_name="overall_attitude",
            output_column_name="attitude_colors",
            colormap=[None, None, None, None, None],
            df=calc_attitude_scores,
            **(params_dict.get("apply_att_colormap") or {}),
        )
        .call()
    )

    generate_att_layers = (
        create_point_layer.validate()
        .handle_errors(task_instance_id="generate_att_layers")
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "fill_color_column": "attitude_colors",
                "legend": {
                    "label_column": "overall_attitude",
                    "color_column": "attitude_colors",
                },
                "tooltip_columns": [
                    "overall_attitude",
                    "attitude_colors",
                    "elephant_sentiment_score",
                ],
                "geodataframe": apply_att_colormap,
            },
            **(params_dict.get("generate_att_layers") or {}),
        )
        .call()
    )

    zoom_att_layers = (
        create_view_state_from_gdf.validate()
        .handle_errors(task_instance_id="zoom_att_layers")
        .partial(
            pitch=0,
            bearing=0,
            gdf=apply_att_colormap,
            **(params_dict.get("zoom_att_layers") or {}),
        )
        .call()
    )

    zip_att_zoom_values = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_att_zoom_values")
        .partial(
            left=generate_att_layers,
            right=zoom_att_layers,
            **(params_dict.get("zip_att_zoom_values") or {}),
        )
        .call()
    )

    draw_att_ecomap = (
        draw_ecomap.validate()
        .handle_errors(task_instance_id="draw_att_ecomap")
        .partial(
            tile_layers=configure_base_maps,
            north_arrow_style={"placement": "top-left"},
            legend_style={"placement": "bottom-right", "title": "Attitude Scores"},
            static=False,
            title=None,
            max_zoom=20,
            **(params_dict.get("draw_att_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers", "view_state"], argvalues=zip_att_zoom_values)
    )

    persist_att_ecomap_urls = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_att_ecomap_urls")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_att_ecomap,
            filename="attitude_scores_community",
            **(params_dict.get("persist_att_ecomap_urls") or {}),
        )
        .call()
    )

    create_att_widgets = (
        create_map_widget_single_view.validate()
        .handle_errors(task_instance_id="create_att_widgets")
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Attitude Scores", **(params_dict.get("create_att_widgets") or {})
        )
        .map(argnames=["view", "data"], argvalues=persist_att_ecomap_urls)
    )

    merge_att_widgets = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="merge_att_widgets")
        .partial(
            widgets=create_att_widgets, **(params_dict.get("merge_att_widgets") or {})
        )
        .call()
    )

    apply_gn_colormap = (
        apply_color_map.validate()
        .handle_errors(task_instance_id="apply_gn_colormap")
        .partial(
            input_column_name="Participant gender",
            output_column_name="gender_colors",
            colormap=[None, None, None],
            df=bin_survey_cols,
            **(params_dict.get("apply_gn_colormap") or {}),
        )
        .call()
    )

    generate_gn_layers = (
        create_point_layer.validate()
        .handle_errors(task_instance_id="generate_gn_layers")
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "fill_color_column": "gender_colors",
                "legend": {
                    "label_column": "Participant gender",
                    "color_column": "gender_colors",
                },
                "tooltip_columns": ["Participant gender", "gender_colors"],
                "geodataframe": apply_gn_colormap,
            },
            **(params_dict.get("generate_gn_layers") or {}),
        )
        .call()
    )

    zoom_gn_layers = (
        create_view_state_from_gdf.validate()
        .handle_errors(task_instance_id="zoom_gn_layers")
        .partial(
            pitch=0,
            bearing=0,
            gdf=apply_gn_colormap,
            **(params_dict.get("zoom_gn_layers") or {}),
        )
        .call()
    )

    zip_gn_zoom_values = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_gn_zoom_values")
        .partial(
            left=generate_gn_layers,
            right=zoom_gn_layers,
            **(params_dict.get("zip_gn_zoom_values") or {}),
        )
        .call()
    )

    draw_gn_ecomap = (
        draw_ecomap.validate()
        .handle_errors(task_instance_id="draw_gn_ecomap")
        .partial(
            tile_layers=configure_base_maps,
            north_arrow_style={"placement": "top-left"},
            legend_style={"placement": "bottom-right", "title": "Gender distribution"},
            static=False,
            title=None,
            max_zoom=20,
            **(params_dict.get("draw_gn_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers", "view_state"], argvalues=zip_gn_zoom_values)
    )

    persist_gn_ecomap_urls = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_gn_ecomap_urls")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_gn_ecomap,
            filename="gender_distribution_ecomap",
            **(params_dict.get("persist_gn_ecomap_urls") or {}),
        )
        .call()
    )

    create_gn_widgets = (
        create_map_widget_single_view.validate()
        .handle_errors(task_instance_id="create_gn_widgets")
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title="Gender", **(params_dict.get("create_gn_widgets") or {}))
        .map(argnames=["view", "data"], argvalues=persist_gn_ecomap_urls)
    )

    merge_gn_widgets = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="merge_gn_widgets")
        .partial(
            widgets=create_gn_widgets, **(params_dict.get("merge_gn_widgets") or {})
        )
        .call()
    )

    generate_ov_layers = (
        create_point_layer.validate()
        .handle_errors(task_instance_id="generate_ov_layers")
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_fill_color": None,
                "legend": {"labels": ["Survey locations"], "colors": [None]},
                "geodataframe": bin_survey_cols,
            },
            **(params_dict.get("generate_ov_layers") or {}),
        )
        .call()
    )

    zoom_ov_layers = (
        create_view_state_from_gdf.validate()
        .handle_errors(task_instance_id="zoom_ov_layers")
        .partial(
            pitch=0,
            bearing=0,
            gdf=bin_survey_cols,
            **(params_dict.get("zoom_ov_layers") or {}),
        )
        .call()
    )

    zip_ov_zoom_values = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_ov_zoom_values")
        .partial(
            left=generate_ov_layers,
            right=zoom_ov_layers,
            **(params_dict.get("zip_ov_zoom_values") or {}),
        )
        .call()
    )

    draw_ov_ecomap = (
        draw_ecomap.validate()
        .handle_errors(task_instance_id="draw_ov_ecomap")
        .partial(
            tile_layers=configure_base_maps,
            north_arrow_style={"placement": "top-left"},
            legend_style={"placement": "bottom-right", "title": "Legend"},
            static=False,
            title=None,
            max_zoom=20,
            **(params_dict.get("draw_ov_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers", "view_state"], argvalues=zip_ov_zoom_values)
    )

    persist_ov_ecomap_urls = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_ov_ecomap_urls")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_ov_ecomap,
            filename="survey_locations_ecomap",
            **(params_dict.get("persist_ov_ecomap_urls") or {}),
        )
        .call()
    )

    create_ov_widgets = (
        create_map_widget_single_view.validate()
        .handle_errors(task_instance_id="create_ov_widgets")
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Survey Locations", **(params_dict.get("create_ov_widgets") or {})
        )
        .map(argnames=["view", "data"], argvalues=persist_ov_ecomap_urls)
    )

    merge_ov_widgets = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="merge_ov_widgets")
        .partial(
            widgets=create_ov_widgets, **(params_dict.get("merge_ov_widgets") or {})
        )
        .call()
    )

    convt_plot_png = (
        zhtml_to_png.validate()
        .handle_errors(task_instance_id="convt_plot_png")
        .partial(
            html_path=[
                draw_survey_pies,
                draw_survey_bar,
                draw_stat_box,
                draw_ols_plots,
                draw_tukey_plots,
            ],
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"wait_for_timeout": 100},
            **(params_dict.get("convt_plot_png") or {}),
        )
        .call()
    )

    convt_ecohtml_png = (
        zhtml_to_png.validate()
        .handle_errors(task_instance_id="convt_ecohtml_png")
        .partial(
            html_path=[
                persist_att_ecomap_urls,
                persist_gn_ecomap_urls,
                persist_ov_ecomap_urls,
            ],
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"wait_for_timeout": 20000},
            **(params_dict.get("convt_ecohtml_png") or {}),
        )
        .call()
    )

    survey_dashboard = (
        gather_dashboard.validate()
        .handle_errors(task_instance_id="survey_dashboard")
        .partial(
            details=workflow_details,
            widgets=[merge_att_widgets, merge_gn_widgets, merge_ov_widgets],
            time_range=time_range,
            groupers=groupers,
            **(params_dict.get("survey_dashboard") or {}),
        )
        .call()
    )

    return survey_dashboard
